dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry install

script:
   - poetry run mypy convpandas
   - poetry run flake8 convpandas
   - poetry run pytest tests

after_success:
  - codecov 

branches:
  only:
  - main
